DROP TABLE IF EXISTS transactions;
DROP TABLE IF EXISTS providers;
DROP TABLE IF EXISTS funds;

CREATE TABLE funds(
  id SERIAL8 PRIMARY KEY,
  category VARCHAR(255)
);

CREATE TABLE providers(
  id SERIAL8 PRIMARY KEY,
  name VARCHAR(255),
  fund_id INT8 REFERENCES funds(id) ON DELETE CASCADE
);

CREATE TABLE transactions(
  id SERIAL8 PRIMARY KEY,
  provider_id INT8 REFERENCES providers(id) ON DELETE CASCADE,
  fund_id INT8 REFERENCES funds(id) ON DELETE CASCADE,
  price NUMERIC
);
